### ISSUE TITLE
np.ravel() support

### ISSUE THREAD

**Issue by DmitryDemidov80** [dpilger26/NumCpp#30]
Hi!
Will be support ravel() method?

**Comment by dpilger26** [comment]
I originally didn't add a ravel() method because it seems pretty redundant to reshape(), however I went ahead and added ravel() for convenience.  

See the NdArray ravel() method documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#aa813af00184616e608feecf30b7aa016).
See the stand-alone ravel() function documentation [here](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#aa8b1d40fcf507ed3d94590844a61f915).

Do a pull on the master branch and you'll be good to go.
