### ISSUE TITLE
Support for multiplying arrays with different data types

### ISSUE THREAD

**Issue by DmitryDemidov80** [dpilger26/NumCpp#31]
Hi!
I'm trying multiply two arrays with different data types:
```
nc::NdArray<int8_t> a({-1,2,-3,4});
nc::NdArray<int16_t> b({22,33,-33,44});
auto m=a*b; // must be -22, 66, 99, 176
```
but get error: no match for ‘operator*’ (operand types are ‘nc::NdArray<signed char>’ and ‘nc::NdArray<short int>’)

If arrays is same data type - ok.

Is it possible to add multiplying different data types?
Thanks!

**Comment by DmitryDemidov80** [comment]
I try it:
```
nc::NdArray<int16_t> a1({1,2,3,4});
nc::NdArray<int8_t> a2({1,2,3,4});
a2.astype<int16_t>();
nc::NdArray<int16_t> m=a1*a2; //must be 1,4,9,16
```
but get error: invalid operands to binary expression ('nc::NdArray<int16_t>' (aka 'NdArray<short>') and 'nc::NdArray<int8_t>' (aka 'NdArray<signed char>'))

Does astype() method works?

**Comment by dpilger26** [comment]
NumCpp deliberately leaves it to the user to do make sure that the types are consistent between arrays.  This is done so that NumCpp does not need to "guess" what output type the user wants.

You are are the right track above by using the astype() method to cast the array to the correct type before multiplying.  However, astype() returns a new array, it does not convert the array in place.  So  your above example should be:
```cpp
nc::NdArray<int16_t> a1({1, 2, 3, 4});
nc::NdArray<int8_t> a2({1, 2, 3, 4});

auto int16Array = a1 * a2.astype<int16_t>(); // will be 1,4,9,16
auto int8Array = a1.astype<int8_t>() * a2; // will be 1,4,9,16
```

**Comment by DmitryDemidov80** [comment]
Ok, thanks!
