### ISSUE TITLE
amin and amax

### ISSUE THREAD

**Issue by aligoglos** [dpilger26/NumCpp#36]
If you implement these methods it will be very useful.
for example in python suppose we have arrays of rectangle points (2 4) so we can find `TopLeft `and `BottomRight `like this :

```
tl = np.amin(pts,1)
br = np.amax(pts,1)
```

**Comment by dpilger26** [comment]
For some reason NumPy has two sets of function pairs min/amin and max/amax that have identical functionality.  Since they are identical, I only implemented one of each in NumCpp.  See the NumCpp documentation for [min](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a1dcd97ed6259f6a019ff8b59f2ae1adc) and [max](https://dpilger26.github.io/NumCpp/doxygen/html/namespacenc.html#a5273d0dac1896f082d185c7f0b90d99f).

Here is your example accomplished with NumCpp:
```cpp
#include "NumCpp.hpp"

#include <iostream>

int main()
{
    auto rectangleCorners = nc::NdArray<nc::uint32>{ {0, 0}, {0, 5}, {5, 0}, {5, 5} };
    auto tl = nc::min(rectangleCorners, nc::Axis::ROW);
    auto br = nc::max(rectangleCorners, nc::Axis::ROW);

    std::cout << "Top Left     = " << tl << std::endl;
    std::cout << "Bottom Right = " << br << std::endl;

    return EXIT_SUCCESS;
}
```

**Comment by aligoglos** [comment]
thanks.
