### ISSUE TITLE
Support for tensors in dimension 4 

### ISSUE THREAD

**Issue by kotbegemot** [dpilger26/NumCpp#40]
I work with tenders of dimension 4 . 
We have to rewrite from python and numpy to C++ . 
If the ability to do so:

```python 
t = t[:,5:, :, :]
t.transpose(0, 2, 3, 1).reshape(-1, 1)
```

Is it possible to simulate behavior that may not exist ?

**Comment by dpilger26** [comment]
No, since NumCpp is limited to 2 dimensional arrays this is not possible.  For operations on arrays greater than 2D I would recommend using a different library such as [TensorFlow](https://www.tensorflow.org/), [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page), or [xtensor](https://xtensor.readthedocs.io/en/latest/).  You can always map the array from these other libraries back into a flattened NumCpp NdArray for use of non-dimensional functions.  See the [examples ](https://github.com/dpilger26/NumCpp/tree/master/examples/InterfaceWithEigen)directory for an example of interfacing back and forth between NumCpp and Eigen.
