### ISSUE TITLE
Hope to develop an Android edition numcpp.

### ISSUE THREAD

**Issue by qq12cvhj** [dpilger26/NumCpp#48]
Is there any possibilities that you will develop an android-edition numcpp？

**Comment by dpilger26** [comment]
Android development has not been on my radar.  However, using the [Android NDK](https://developer.android.com/ndk/downloads), and linking the [LLVM libc++](https://developer.android.com/ndk/guides/cpp-support#system) (which says it is fully C++11 complaint) that comes bundled with it looks like it _should_ get you there.  Having never developed for Android before though I can't say for sure.  Do you know of any thing else that NumCpp would require in order to be able to be used in Android development?  I'd imagine that there would likely also have to be some fiddling to get some of the Boost dependencies to compile correctly.

**Comment by qq12cvhj** [comment]
I'm not for sure whether on android devices boost differs from on other platforms.If there not exists any third party libs except libboost,I guess it will work.Here's the [boost for android](https://github.com/moritz-wundke/Boost-for-Android)，perhaps not an official edition.
I'm working on audio process,where numpy will work.But on android devices the python numpy is impossible to deploy.
It's OK,I just think it will be better if numcpp works on other platforms like Android /iOS. You can do some test,,,emmm,if you have more spare time.
Thanks for your reply!

**Comment by dpilger26** [comment]
Well, go ahead and give it a try and let me know if you run into any issues.

**Comment by qq12cvhj** [comment]
No problem.
