### ISSUE TITLE
How to init NdArray with 2d array?

### ISSUE THREAD

**Issue by AlbertoWang** [dpilger26/NumCpp#88]
**Describe the solution you'd like**
When I init a NdArray with a 2d array, what should I do with code? I tried code as follows:
```c++
float a[4][3] = {{0.0, 0.0, 0.0},
                     {0.0, 0.0, 1.0},
                     {5.0, 5.0, 5.0},
                     {1.0, 1.0, 1.0}};
float(*b)[3];
b = a;
nc::NdArray<float> x = nc::NdArray<float>(a, 4, 3); // not worked
nc::NdArray<float> x = nc::NdArray<float>(b, 4, 3); // not worked
```
My purpose is write a Python extension with C++. I chose `numcpp` for finishing some tasks which are done by `numpy` in Python, so the input of functions are lists from Python in form of 2d array such as `const int (*a)[3]`, I need to initial `nc::NdArray<dtype>` via `a`, how can I do that? Or is there some better ways to make C++ extension for Python? What I know is using `ctypes`

**Comment by dpilger26** [comment]
The `NdArray` constructor that you are trying to use is [this one](https://dpilger26.github.io/NumCpp/doxygen/html/classnc_1_1_nd_array.html#a42c487740a599fc7906acbeea2fa766d) which takes in a pointer to an array and the array dimensions.  However instead of passing in a `float*` like would be required, you are passing in a `float(*)[3]`,  So you would need to pass in `a[0]` and `b[0]` instead.

```cpp
#include "NumCpp.hpp"
 
#include <cstdlib>
#include <iostream>
 
int main()
{
	float a[4][3] = {{0.0, 0.0, 0.0},
			        {0.0, 0.0, 1.0},
				{5.0, 5.0, 5.0},
				{1.0, 1.0, 1.0}};
	float (*b)[3] = a;

	auto x_a = nc::NdArray<float>(a[0], 4, 3); // makes a copy
	auto x_b = nc::NdArray<float>(b[0], 4, 3); // makes a copy

	x_b *= 2.0f; // just to show they are different

	std::cout << "x_a = \n" << x_a << '\n';
	std::cout << "x_b = \n" << x_b << '\n';

	// you can also use NdArray as a non-owning shell
	auto x_a_shell = nc::NdArray<float>(a[0], 4, 3, false); // non-owning shell
	x_a_shell(0, 0) = 7.0f;

	std::cout << "x_a_shell(0, 0) = " << x_a_shell(0, 0) << ", a[0][0] = " << a[0][0] << '\n';
		 
	return EXIT_SUCCESS;
}
```

This example outputs:

```bash
x_a =
[[0, 0, 0, ]
[0, 0, 1, ]
[5, 5, 5, ]
[1, 1, 1, ]]

x_b =
[[0, 0, 0, ]
[0, 0, 2, ]
[10, 10, 10, ]
[2, 2, 2, ]]

x_a_shell(0, 0) = 7, a[0][0] = 7
```

Also, for writing Python C++ extensions I would highly recommend using the [Pybind11](https://github.com/pybind/pybind11) library instead of ctypes.

**Comment by AlbertoWang** [comment]
Thanks for your help!

**Comment by dpilger26** [comment]
You would use the `data()` method, or if you would like `NdArray` to relinquish ownership of the underlying array you would use `dataRelease()`.

**Comment by AlbertoWang** [comment]
Thank you for your answer! Best wishes!
