### ISSUE TITLE
compile with c++17 is 10 times slower than with c++14 in vs2017

### ISSUE THREAD

**Issue by PascalZh** [dpilger26/NumCpp#99]
**Describe the bug**
I translate some numpy codes into numcpp and compile it with c++17 in vs2017, it turns out the codes is much more slower than that with c++14. Anybody know how that happens?

**To Reproduce**
I'm sorry my codes are not propriate for presenting here. But I find some codes like `v = (a -  b) / t` is 10 times slower than compiled with c++14.

**Expected behavior**
c++17 should be the same proficient as the c++14.

**Additional context**
Other project settings are default.

**Comment by dpilger26** [comment]
C++17 first introduced the parallel execution policies (multi-threaded) into the STL for the `<algorithm>` header.  `NumCpp` optionally utilizes the parallel execution policy for a lot of it's operations while using a C++17 compliant compiler,  This can have major performance impacts both directions.  For operations and arrays with a large number of elements it can have a large speed up.  However, for operations and arrays with smaller number of elements, this can actually slow things down due to the additional overhead of spawning and keeping track of multiple threads.  You can turn off the multi-threading in `NumCpp` by defining the compiler flag `NO_MULTITHREAD` in your project and this should bring your performance back in line with your C++14 version.

**Comment by PascalZh** [comment]
@dpilger26 Thanks. But I think it should be documented.

**Comment by dpilger26** [comment]
I agree it should be better documented. Documentation is tough and an always evolving thing to try to capture everything. I've made a note to capture this better in the next release.
